// menuMapper.tsx

import React from "react";
import type { MenuProps } from "antd";

import {
  PieChartOutlined,
  DesktopOutlined,
  ContainerOutlined,
  MailOutlined,
  AppstoreOutlined,
  SettingOutlined,
  MenuOutlined,
  HomeOutlined,
  UserOutlined,
  TeamOutlined,
  DashboardOutlined,
  BookOutlined,
  CalendarOutlined,
  CloudOutlined,
  FileOutlined,
  FolderOutlined,
  LockOutlined,
  SafetyCertificateOutlined,
  BellOutlined,
  SearchOutlined,
  EditOutlined,
  DeleteOutlined,
  PlusOutlined,
  CheckOutlined,
  CloseOutlined,
  InfoCircleOutlined,
  ExclamationCircleOutlined,
  BarChartOutlined,
  LineChartOutlined,
  ShoppingOutlined,
  ShoppingCartOutlined,
  KeyOutlined,
  GlobalOutlined,
  HistoryOutlined,
  AuditOutlined,
  UnlockOutlined,
  ContactsOutlined,
  BranchesOutlined,
  BuildOutlined,
  DatabaseOutlined,
  NodeIndexOutlined,
  PartitionOutlined,
  DeploymentUnitOutlined,
  SyncOutlined,
  PoweroffOutlined,
  FileTextOutlined,
  FileDoneOutlined,
  ProjectOutlined,
  PrinterOutlined,
  ShareAltOutlined,
  ToolOutlined,
  ApiOutlined,
  LinkOutlined,
  PaperClipOutlined,
} from "@ant-design/icons";

import type { MenuDto } from "../models/DTO/MenuDTO";

type MenuItem = Required<MenuProps>["items"][number];

export const iconMap: Record<string, React.ReactNode> = {
  PieChartOutlined: <PieChartOutlined />,
  DesktopOutlined: <DesktopOutlined />,
  ContainerOutlined: <ContainerOutlined />,
  MailOutlined: <MailOutlined />,
  AppstoreOutlined: <AppstoreOutlined />,
  SettingOutlined: <SettingOutlined />,
  MenuOutlined: <MenuOutlined />,
  HomeOutlined: <HomeOutlined />,
  UserOutlined: <UserOutlined />,
  TeamOutlined: <TeamOutlined />,
  DashboardOutlined: <DashboardOutlined />,
  BookOutlined: <BookOutlined />,
  CalendarOutlined: <CalendarOutlined />,
  CloudOutlined: <CloudOutlined />,
  FileOutlined: <FileOutlined />,
  FolderOutlined: <FolderOutlined />,
  LockOutlined: <LockOutlined />,
  SafetyCertificateOutlined: <SafetyCertificateOutlined />,
  BellOutlined: <BellOutlined />,
  SearchOutlined: <SearchOutlined />,
  EditOutlined: <EditOutlined />,
  DeleteOutlined: <DeleteOutlined />,
  PlusOutlined: <PlusOutlined />,
  CheckOutlined: <CheckOutlined />,
  CloseOutlined: <CloseOutlined />,
  InfoCircleOutlined: <InfoCircleOutlined />,
  ExclamationCircleOutlined: <ExclamationCircleOutlined />,
  BarChartOutlined: <BarChartOutlined />,
  LineChartOutlined: <LineChartOutlined />,
  ShoppingOutlined: <ShoppingOutlined />,
  ShoppingCartOutlined: <ShoppingCartOutlined />,
  KeyOutlined: <KeyOutlined />,
  GlobalOutlined: <GlobalOutlined />,
  HistoryOutlined: <HistoryOutlined />,
  AuditOutlined: <AuditOutlined />,
  UnlockOutlined: <UnlockOutlined />,
  ContactsOutlined: <ContactsOutlined />,
  BranchesOutlined: <BranchesOutlined />,
  BuildOutlined: <BuildOutlined />,
  DatabaseOutlined: <DatabaseOutlined />,
  NodeIndexOutlined: <NodeIndexOutlined />,
  PartitionOutlined: <PartitionOutlined />,
  DeploymentUnitOutlined: <DeploymentUnitOutlined />,
  SyncOutlined: <SyncOutlined />,
  PoweroffOutlined: <PoweroffOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  FileDoneOutlined: <FileDoneOutlined />,
  ProjectOutlined: <ProjectOutlined />,
  PrinterOutlined: <PrinterOutlined />,
  ShareAltOutlined: <ShareAltOutlined />,
  ToolOutlined: <ToolOutlined />,
  ApiOutlined: <ApiOutlined />,
  LinkOutlined: <LinkOutlined />,
  PaperClipOutlined: <PaperClipOutlined />,
};

export function toMenuItems(menus: MenuDto[]): MenuItem[] {
  return menus.map((m) => ({
    key: m.Url ?? m.MenuId,
    label: m.MenuName,
    icon: m.Icon ? iconMap[m.Icon] : undefined,
    children: m.Children
      ? toMenuItems(m.Children)
      : undefined,
  }));
}